#binds azure devops service account to a RBAC role
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.rolebinding.azdevops.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.role.azdevops.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceaccount.azdevops.name }}
  namespace: {{ .Values.serviceaccount.azdevops.namespace }}