#creates azure devops service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceaccount.azdevops.name }}
  namespace: {{ .Values.serviceaccount.azdevops.namespace }}